### ISSUE TITLE
Wow, cool original name for a discord bot, very cool

### ISSUE THREAD

**Issue by tomvanwoow** [wlw-code/Quaestor#1]
Quaestor? How the heck did you come up with that? It's genius. Simple and original, not plagiarised in any way.

**Comment by wlw-code** [comment]
Are you referencing your Quest bot?

**Comment by tomvanwoow** [comment]
Perhaps

**Comment by tomvanwoow** [comment]
I really don't care though, I was joking

**Comment by wlw-code** [comment]
Alright lol well if you must know, the name was chosen because a quaestor was a position in the Roman Empire that was similar to an assistant to the Emperor, so the bot was intended to be similar to that but serving the owner of the Discord server. If you look into the code, the Scribe class communicates between the system and the user, like a scribe in the Roman Empire.

So there's that useless factoid :P
